In [1]:
import pandas as pd

In [2]:
df = pd.read_json("../../raw_jobs_2026-07-13.json")

df.tail()

,title,company,location,country,salary_min,salary_max,employment_type,date_posted,is_remote,description,apply_link
163,SQA Intern (Morning Shift),DotClick,Karachi,PK,NaN,NaN,Full-time,NaN,False,We are seeking a highly motivated and detail-o...,https://bebee.com/pk/jobs/sqa-intern-morning-s...
164,Senior SQA Engineer – AI/LLM Conversational Qu...,Techsurge Private Limited,Karachi,PK,NaN,NaN,Full-time,NaN,False,Techsurge Private Limited is seeking an experi...,https://pk.jobrapido.com/jobpreview/5719162394...
165,Mid-Level SQA,Digital Gravity,Karachi,PK,NaN,NaN,Full-time,2026-07-11T00:00:00.000Z,False,The ideal candidate for this position should h...,https://pk.jooble.org/jdp/-8901619374353891048
166,SQA Engineer- Associate,Squarera,Karachi,PK,NaN,NaN,Full-time,2026-06-20T00:00:00.000Z,False,"Job description\n\nAt Squarera, we pride ourse...",https://bebee.com/pk/jobs/sqa-engineer-associa...
167,Senior SQA Engineer - AI-Driven Automation Leader,Pakistan Single Window,Karachi,PK,NaN,NaN,Full-time,2026-07-09T00:00:00.000Z,False,Pakistan Single Window seeks a skilled QA Engi...,https://pk.jooble.org/jdp/6836092669775078420

In [3]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 168 entries, 0 to 167
Data columns (total 11 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   title            168 non-null    str
 1   company          168 non-null    str
 2   location         167 non-null    str
 3   country          167 non-null    str
 4   salary_min       0 non-null      float64
 5   salary_max       0 non-null      float64
 6   employment_type  167 non-null    str
 7   date_posted      96 non-null     str
 8   is_remote        168 non-null    bool
 9   description      168 non-null    str
 10  apply_link       168 non-null    str
dtypes: bool(1), float64(2), str(8)
memory usage: 87.0 KB

In [4]:
df.drop(['salary_min', 'salary_max'], axis=1, inplace=True)

In [5]:
df['date_posted'] = pd.to_datetime(df['date_posted'], errors='coerce')
df['date_posted'] = df['date_posted'].dt.tz_localize(None)
df['date_posted'] = df['date_posted'].astype('datetime64[ns]')

In [6]:
# df['date_posted'] = date_posted
df['date_posted_month'] = df['date_posted'].dt.month
df['date_posted_year'] = df['date_posted'].dt.year

df.tail(20)

,title,company,location,country,employment_type,date_posted,is_remote,description,apply_link,date_posted_month,date_posted_year
148,Senior Erp Functional Consultant,Leaders Corporate,Karachi,PK,Full-time,NaT,False,This is a full-time hybrid role for a Senior E...,https://www.getpakjob.com/jobs/view/senior-erp...,NaN,NaN
149,Sr. SQA Automation Analyst,Contour Software,Karachi,PK,Full-time,2026-07-07,False,About Contour Contour Software has grown from ...,https://bebee.com/pk/jobs/sr-sqa-automation-an...,7.0,2026.0
150,SQA Automation Engineer,Urban Ridge Supplies,Karachi,PK,Full-time,NaT,False,Role Overview\nWe are looking for an SQA Autom...,https://jobs.urbanridgesupplies.com/jobs/72357...,NaN,NaN
151,Senior SQA Engineer: Azure Security & Automation,Digital,Karachi,PK,Full-time,2026-07-09,False,Digital is seeking a Software Quality Assuranc...,https://pk.jooble.org/jdp/-6831015283142133077,7.0,2026.0
152,Software Quality Assurance Engineer - (AI Driv...,iTackSolutions,Karachi,PK,Full-time,NaT,False,We’re looking for an experienced Senior SQA En...,https://bebee.com/pk/jobs/software-quality-ass...,NaN,NaN
153,"Lead SQA Manager: Automation, QA Strategy & Me...",Pakistan Single Window (PSW),Karachi,PK,Full-time,2026-06-23,False,Pakistan Single Window (PSW) is looking for a ...,https://pk.jobrapido.com/jobpreview/7641013440...,6.0,2026.0
154,Onsite QA Engineer - Karachi: Web & App Testing,Bits Generation,Karachi,PK,Full-time,2026-07-08,False,Bits Generation is hiring a QA Engineer in Kar...,https://pk.jooble.org/jdp/4490691573844313483,7.0,2026.0
155,Senior SQA Engineer,HR WAYS,Karachi,PK,Full-time,NaT,False,About the job Senior SQA Manual Engineer | Ons...,https://www.bayt.com/en/pakistan/jobs/senior-s...,NaN,NaN
156,Sr. SQA Engineer,Eocean,Karachi,PK,Full-time,2026-07-10,False,Requirements:\n• Analyze bugs and errors found...,https://pk.jooble.org/jdp/5938452550771214237,7.0,2026.0
157,Senior SQA Automation Analyst — End-to-End Tes...,Contour Software,Karachi,PK,Full-time,NaT,False,Contour Software is looking for a Sr. SQA Auto...,https://pk.jobrapido.com/jobpreview/3976237762...,NaN,NaN
158,SQA Engineer.,Think Digitally,Karachi,PK,Full-time,2026-07-09,False,Key responsibilities:\n• Develop and execute t...,https://pk.jooble.org/jdp/-1644260068084053620,7.0,2026.0
159,SQA Engineer - Immediate Start (Manual & Autom...,Digital Gravity,Karachi,PK,Full-time,2026-07-11,False,A technology company in Pakistan seeks a skill...,https://pk.jooble.org/jdp/-648096675263358167,7.0,2026.0
160,Analyst SQA Engineer (Contractual),Pakistan Single Window,Karachi,PK,Contractor,NaT,False,• Execute test cases to evaluate software func...,https://bebee.com/pk/jobs/analyst-sqa-engineer...,NaN,NaN
161,Senior SQA Engineer – Manual & Automation (Java),HR Ways,Karachi,PK,Full-time,NaT,False,HR Ways is seeking an experienced Lead SQA Man...,https://pk.jobrapido.com/jobpreview/7815375884...,NaN,NaN
162,Lead SQA Automation Engineer - Onsite Karachi ...,HR WAYS,Karachi,PK,Full-time,NaT,False,A digital solutions provider in Karachi is see...,https://pk.jobrapido.com/jobpreview/1300427902...,NaN,NaN
163,SQA Intern (Morning Shift),DotClick,Karachi,PK,Full-time,NaT,False,We are seeking a highly motivated and detail-o...,https://bebee.com/pk/jobs/sqa-intern-morning-s...,NaN,NaN
164,Senior SQA Engineer – AI/LLM Conversational Qu...,Techsurge Private Limited,Karachi,PK,Full-time,NaT,False,Techsurge Private Limited is seeking an experi...,https://pk.jobrapido.com/jobpreview/5719162394...,NaN,NaN
165,Mid-Level SQA,Digital Gravity,Karachi,PK,Full-time,2026-07-11,False,The ideal candidate for this position should h...,https://pk.jooble.org/jdp/-8901619374353891048,7.0,2026.0
166,SQA Engineer- Associate,Squarera,Karachi,PK,Full-time,2026-06-20,False,"Job description\n\nAt Squarera, we pride ourse...",https://bebee.com/pk/jobs/sqa-engineer-associa...,6.0,2026.0
167,Senior SQA Engineer - AI-Driven Automation Leader,Pakistan Single Window,Karachi,PK,Full-time,2026-07-09,False,Pakistan Single Window seeks a skilled QA Engi...,https://pk.jooble.org/jdp/6836092669775078420,7.0,2026.0

In [7]:
print(df.head())

                                          title  \
0  Senior Software Engineer - Python (4+ Years)
1        Python/Django Developer - CipherStudio
2                        Senior Python Engineer
3                    Software Engineer (Python)
4         Jr. Backend Developer (Python/Django)

                                 company location country employment_type  \
0                        Primaconsulting  Karachi      PK       Full-time
1  Gravity Engineering Services Pvt Ltd.  Karachi      PK       Full-time
2                 Arc Inventador Pvt Ltd      NaN     NaN       Full-time
3                        Primaconsulting  Karachi      PK       Full-time
4                   Polaris Technologies  Karachi      PK       Full-time

  date_posted  is_remote                                        description  \
0  2026-07-10      False  Senior Software Engineer – Python (4+ Years)\n...
1  2026-07-11      False  Python/Django Developer at CipherStudio\nKey t...
2         NaT      False  Key ResponsibilitiesBackend & API Development\...
3  2026-07-09      False  We are looking for a Software Engineer (Python...
4         NaT      False  Job Description: Polaris Technologies is seeki...

                                          apply_link  date_posted_month  \
0      https://pk.jooble.org/jdp/6524210474955788246                7.0
1  https://pk.jobrapido.com/jobpreview/8576089350...                7.0
2  https://www.indeed.com/viewjob?jk=3f343bb587ca...                NaN
3     https://pk.jooble.org/jdp/-2521161279209618823                7.0
4         https://www.mustakbil.com/jobs/job/1430523                NaN

   date_posted_year
0            2026.0
1            2026.0
2               NaN
3            2026.0
4               NaN

In [ ]:
import re

def extract_seniority(title: str) -> str:
    if not title:
        return "unspecified"
    
    title_lower = title.lower()
    
    if any(x in title_lower for x in ["fresher","intern", "internship", "trainee"]):
        return "intern"
    elif any(x in title_lower for x in ["junior", "jr.", "jr ", "entry"]):
        return "junior"
    elif any(x in title_lower for x in ["mid", "mid-level", "intermediate"]):
        return "mid"
    elif any(x in title_lower for x in ["architect", "contract","senior", "sr.", "sr ", "lead", "principal","consultant","engineer","specialist"]):
        return "senior"
    else:
        return "unspecified"

def extract_job_type(title: str) -> str:
    if not title:
        return "unspecified"
    
    title_lower = title.lower()

    if any(x in title_lower for x in ["sqa", "qa"]):
        return "SQA Automation/Testing"
    elif any(x in title_lower for x in ["python", "django", "dotnet","full","stack","angular", "web", "mern", "node.js", "react.js", "wordpress", ".net"]):
        return "Full Stack Developer"
    elif any(x in title_lower for x in ["ai", "ml", "ai/ml","machine learning","ai engineer"]):
        return "AI/ML Engineer"
    elif any(x in title_lower for x in ["cybersecurity", "soc", "penetration", "threat", "cyber","security"]):
        return "CyberSecurity"
    elif any(x in title_lower for x in ["sap","abap"]):
        return "SAP Consultancy"
    elif any(x in title_lower for x in ["odoo"]):
        return "Odoo Functional Consultant"
    elif any(x in title_lower for x in ["erp"]):
        return "ERP Specialist"
    elif any(x in title_lower for x in ["cloud","ops","devops","ci","cd"]):
        return "DevOps/MLOps"
    elif any(x in title_lower for x in ["networking", "it","troubleshooting","ccna"]):
        return "IT/Networking"
    else:
        return "unspecified"

In [58]:
df['seniority'] = df["title"].apply(extract_seniority)

print(df['seniority'].value_counts())

seniority
senior         118
unspecified     31
intern           8
junior           7
mid              4
Name: count, dtype: int64

In [62]:
df[df['seniority'] == 'junior'][['title', 'company']].head(20)

                                                 title               company
4                Jr. Backend Developer (Python/Django)  Polaris Technologies
12       Junior Python Django Developer (AI/LLM Focus)  Polaris Technologies
15   Junior Python Django Developer (AI/LLM Focus) ...  Polaris Technologies
19   Junior Python Developer (Fresh Graduate / 6 Mo...              Bashalog
51                   Jr WordPress Full-Stack Developer          ITX-Solution
120        Entry-Level ERP & SAP Functional Consultant               QBS Co.
136                  Junior Odoo Functional Consultant             iPlexSoft

In [39]:
df['job_type'] = df["title"].apply(extract_job_type)

print(df['job_type'].value_counts())

job_type
Full Stack Developer          41
AI/ML Engineer                34
SQA Automation/Testing        23
DevOps/MLOps                  19
CyberSecurity                 19
SAP Consultancy               19
Odoo Functional Consultant    11
ERP Specialist                 2
Name: count, dtype: int64

In [41]:
# Display the original job titles and companies for the 'unspecified' rows
df[df['job_type'] == 'AI/ML Engineer'][['title', 'company']]

,title,company
20,AI Automation Engineer - Flexible Hours & Impact,Emeraldxglobal
21,Senior IT Infrastructure Engineer — AI-Driven ...,United States Digital Space LLC
22,ML/AI Ops,Al Watania Agriculture Company
23,AI Automation Expert,Emeraldxglobal
24,AI Automation & Growth Systems Engineer,Enum Digital
26,AI Software Creator / AI Automation Specialist,Granule Services
27,AI Automation Developer,Artistic Milliners
28,AI Application & Automation Engineer,Toy Souk
32,Ai Automation and Reporting Engineer,Xper2Go Pvt. Ltd.
33,Principal Software & AI Engineer - Pakistan,Volga Partners
35,Senior GenAI Engineer - AgenticAI,NorthBay
36,AI Automation Engineer: N8N Workflows & AI Agents,HR Ways
37,AI Platform Engineer (Gen AI),Hopeghospital
57,ML/AI Ops,Al Watania Agriculture Company
58,"Machine Learning Engineer - Onsite Karachi, Gr...",Techelix Private Limited
59,"Machine Learning Engineer – Onsite Karachi, Gr...",Techelix Private Limited
60,Machine Learning Engineer Jobs in Karachi,Cosmoquick
61,Senior ML Engineer,Hopeghospital
62,AI /ML Engineer,Oxiliry
63,Machine Learning & Computer Vision Engineer,AHOY
64,Senior Machine Learning Engineer Jobs in Karachi,Cosmoquick
66,Software Design Engineer (AI & Machine Learning),Teresol Pvt. Ltd
67,Applied AI & ML Engineer — Production Systems ...,Albi
68,AI Engineer — Build Next-Gen ML Solutions,Visiontact
69,Staff/Senior Software Consultant - Machine Lea...,10Pearls
70,Senior ML Engineer: Production AI & Business I...,BRKZ
71,Lead AI Engineer,Easy Recruitment PK
72,Machine Learning Engineer - Build Models to El...,StarsOfTheShow
73,React AI Engineer (Immediately joiner),Getweys
74,Senior AI/Machine Learning Engineer,Devsinc
75,Sr. Ai Engineer With Rag Experience,SOC Solutions LLC
97,AI Cybersecurity Red Team Engineer – On-Prem,Xenon Seven
99,AI Cybersecurity Architect (Governance & Contr...,Xenon Seven
105,SOC Trainee: Hands-on Security & Mentorship Pa...,TISS